server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: 
    password: 
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true

OPENAI_API_KEY: 
OPENAI_ORGANIZATION: 
SECRET: 
GMAIL_USERNAME: 
GMAIL_PASSWORD: 
GMAIL_SMTP: 
GMAIL_PORT: